name: Deploy

on:
  push:
    branches: [ "main", "github-actions" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/625646421163/locations/global/workloadIdentityPools/github-actions-pool-2/providers/github-actions'
        service_account: 'github-actions@kiyocy24.iam.gserviceaccount.com'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v0'
      with:
        name: 'urchecker'
        runtime: 'go116'
        region: 'asia-northeast1'
        entry_point: 'urChecker'
        source_dir: 'urchecker'
        event_trigger_type: 'pubsub'
        event_trigger_resource: '${{ secrets.DEPLOY_CF_EVENT_PUBSUB_TOPIC }}'

